apiVersion: skaffold/v2alpha3
kind: Config
deploy:
    kubectl:
        manifests:
            - ./infra/k8s/*
build:
    local:
        push: false
    artifacts:
        - image: jcq012/client
          context: ./packages/black-tickets-client
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: '**/*.ts'
                    dest: .
        - image: jcq012/auth-service
          context: . # run from
          docker:
              dockerfile: ./packages/black-tickets-auth/Dockerfile
          sync:
              manual:
                  - src: './packages/black-tickets-auth/src/**/*.ts'
                    dest: .
        - image: jcq012/main-service
          context: . # run from
          docker:
              dockerfile: ./packages/black-tickets-main/Dockerfile
          sync:
              manual:
                  - src: './packages/black-tickets-main/src/**/*.ts'
                    dest: .     
        - image: jcq012/order-service
          context: . # run from
          docker:
              dockerfile: ./packages/black-tickets-order/Dockerfile
          sync:
              manual:
                  - src: './packages/black-tickets-order/src/**/*.ts'
                    dest: .
        - image: jcq012/expiration-service
          context: . # run from
          docker:
              dockerfile: ./packages/black-tickets-expiration/Dockerfile
          sync:
              manual:
                  - src: './packages/black-tickets-expiration/src/**/*.ts'
                    dest: .
