apiVersion: skaffold/v2alpha3
kind: Config
deploy:
    kubectl:
        manifests:
            - ./infra/k8s/*
build:
    local:
        push: false
    artifacts:
        - image: jcq012/auth-service
          context: packages/black-tickets-auth # run from
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: 'src/**/*.ts'
                    dest: .
        - image: jcq012/main-service
          context: packages/black-tickets-main # run from
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: 'src/**/*.ts'
                    dest: .
        - image: jcq012/client
          context: packages/black-tickets-client
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: '**/*.ts'
                    dest: .
