apiVersion: skaffold/v2alpha3
kind: Config
deploy:
    kubectl:
        manifests:
            - ./infra/k8s/*
build:
    local:
        push: false
    artifacts:
        - image: jcq012/auth-service
          context: .
          docker:
              dockerfile: packages/ticket-auth/Dockerfile
          sync:
              manual:
                  - src: 'src/**/*.ts'
                    dest: .
        - image: jcq012/ticket-main-service
          context: .
          docker:
              dockerfile: packages/ticket-main/Dockerfile
          sync:
              manual:
                  - src: 'src/**/*.ts'
                    dest: .
        - image: jcq012/client
          context: ./packages/ticket-client
          docker:
              dockerfile: packages/ticket-client/Dockerfile
          sync:
              manual:
                  - src: '**/*.ts'
                    dest: .
