name: auth-build

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: docker build -f packages/black-tickets-auth/Dockerfile -t jcq012/auth-service .
