name: auth-build

on:
  pull_request:
    paths:
      - 'packages/black-tickets-auth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Image and Run Test
        run: docker build -f packages/black-tickets-auth/Dockerfile -t jcq012/auth-service .
      - name: Login to Docker
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push jcq012/auth-service
