name: tests

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - uses: borales/actions-yarn@v3.0.0

     - name: Install Dependency
       run: yarn install

     - name: Bootstrap
       run: yarn bootstrap

     - name: Run auth service test
       run: cd packages/black-tickets-auth/ && yarn run test:ci
