name: tests

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - uses: borales/actions-yarn@v3.0.0
     - run: cd packages/black-tickets-auth/ && yarn install && yarn run test:ci
